<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class KebayaSeeder extends Seeder
{
    public function run()
    {
        $data = [
            // ====================================================================
            // Kategori 1: Kebaya Kutu Baru
            // ====================================================================
            ['id_kategori' => 1, 'nama_kebaya' => 'Kutu Baru Merah Delima', 'slug' => 'kutu-baru-merah-delima', 'deskripsi' => 'Kebaya Kutu Baru klasik berwarna merah delima yang mempesona, bahan katun primisima.', 'ukuran_tersedia' => 'S,M,L', 'harga_sewa' => 150000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 1],
            ['id_kategori' => 1, 'nama_kebaya' => 'Kutu Baru Bunga Melati', 'slug' => 'kutu-baru-bunga-melati', 'deskripsi' => 'Kebaya Kutu Baru dengan motif bunga melati putih yang lembut, cocok untuk acara formal.', 'ukuran_tersedia' => 'M,L', 'harga_sewa' => 175000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 1],
            ['id_kategori' => 1, 'nama_kebaya' => 'Kutu Baru Klasik Jogja', 'slug' => 'kutu-baru-klasik-jogja', 'deskripsi' => 'Gaya otentik Kutu Baru dari Yogyakarta, bahan lurik halus.', 'ukuran_tersedia' => 'Semua Ukuran', 'harga_sewa' => 200000, 'stok' => 3, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 1, 'nama_kebaya' => 'Kutu Baru Biru Langit', 'slug' => 'kutu-baru-biru-langit', 'deskripsi' => 'Kebaya Kutu Baru berwarna biru langit yang cerah dan menenangkan.', 'ukuran_tersedia' => 'S,M', 'harga_sewa' => 160000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 1, 'nama_kebaya' => 'Kutu Baru Hijau Pandan', 'slug' => 'kutu-baru-hijau-pandan', 'deskripsi' => 'Warna hijau pandan yang sejuk pada kebaya Kutu Baru, bahan katun toyobo.', 'ukuran_tersedia' => 'M,L,XL', 'harga_sewa' => 180000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'disewa', 'rekomendasi' => 0],
            ['id_kategori' => 1, 'nama_kebaya' => 'Kutu Baru Motif Parang', 'slug' => 'kutu-baru-motif-parang', 'deskripsi' => 'Perpaduan Kutu Baru dengan motif batik parang yang gagah.', 'ukuran_tersedia' => 'L,XL', 'harga_sewa' => 225000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 1, 'nama_kebaya' => 'Kutu Baru Ungu Anggrek', 'slug' => 'kutu-baru-ungu-anggrek', 'deskripsi' => 'Kebaya Kutu Baru elegan dengan warna ungu anggrek yang mewah.', 'ukuran_tersedia' => 'M,L', 'harga_sewa' => 190000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 1, 'nama_kebaya' => 'Kutu Baru Polos Hitam', 'slug' => 'kutu-baru-polos-hitam', 'deskripsi' => 'Kebaya Kutu Baru hitam polos yang versatile untuk berbagai acara.', 'ukuran_tersedia' => 'Semua Ukuran', 'harga_sewa' => 150000, 'stok' => 3, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 1, 'nama_kebaya' => 'Kutu Baru Kuning Kenanga', 'slug' => 'kutu-baru-kuning-kenanga', 'deskripsi' => 'Warna kuning kenanga yang ceria pada kebaya Kutu Baru.', 'ukuran_tersedia' => 'S,M,L', 'harga_sewa' => 170000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 1, 'nama_kebaya' => 'Kutu Baru Coklat Batik', 'slug' => 'kutu-baru-coklat-batik', 'deskripsi' => 'Kebaya Kutu Baru dengan kain batik sogan berwarna coklat klasik.', 'ukuran_tersedia' => 'M,L,XL', 'harga_sewa' => 210000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],

            // ====================================================================
            // Kategori 2: Kebaya Kartini
            // ====================================================================
            ['id_kategori' => 2, 'nama_kebaya' => 'Kartini Putih Suci', 'slug' => 'kartini-putih-suci', 'deskripsi' => 'Kebaya Kartini panjang berwarna putih bersih, ideal untuk acara resmi dan sakral.', 'ukuran_tersedia' => 'S,M,L', 'harga_sewa' => 200000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 1],
            ['id_kategori' => 2, 'nama_kebaya' => 'Kartini Merah Marun', 'slug' => 'kartini-merah-marun', 'deskripsi' => 'Kebaya Kartini dengan warna merah marun yang anggun dan berwibawa.', 'ukuran_tersedia' => 'M,L,XL', 'harga_sewa' => 225000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 1],
            ['id_kategori' => 2, 'nama_kebaya' => 'Kartini Brokat Jepara', 'slug' => 'kartini-brokat-jepara', 'deskripsi' => 'Sentuhan modern pada Kebaya Kartini dengan bahan brokat dari Jepara.', 'ukuran_tersedia' => 'M,L', 'harga_sewa' => 250000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 2, 'nama_kebaya' => 'Kartini Bordir Bunga', 'slug' => 'kartini-bordir-bunga', 'deskripsi' => 'Kebaya Kartini dihiasi bordir bunga manual yang detail dan cantik.', 'ukuran_tersedia' => 'S,M', 'harga_sewa' => 230000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 2, 'nama_kebaya' => 'Kartini Hitam Elegan', 'slug' => 'kartini-hitam-elegan', 'deskripsi' => 'Kebaya Kartini hitam polos yang memberikan kesan elegan dan langsing.', 'ukuran_tersedia' => 'Semua Ukuran', 'harga_sewa' => 210000, 'stok' => 3, 'foto' => 'default.png', 'status' => 'disewa', 'rekomendasi' => 0],
            ['id_kategori' => 2, 'nama_kebaya' => 'Kartini Sutra Coklat', 'slug' => 'kartini-sutra-coklat', 'deskripsi' => 'Terbuat dari bahan sutra ATBM berwarna coklat keemasan yang mewah.', 'ukuran_tersedia' => 'L,XL', 'harga_sewa' => 300000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 2, 'nama_kebaya' => 'Kartini Biru Dongker', 'slug' => 'kartini-biru-dongker', 'deskripsi' => 'Warna biru dongker (navy) yang klasik pada model Kartini.', 'ukuran_tersedia' => 'M,L', 'harga_sewa' => 220000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 2, 'nama_kebaya' => 'Kartini Motif Kupu', 'slug' => 'kartini-motif-kupu', 'deskripsi' => 'Kebaya Kartini dengan bordiran motif kupu-kupu yang unik.', 'ukuran_tersedia' => 'S,M,L', 'harga_sewa' => 240000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 2, 'nama_kebaya' => 'Kartini Hijau Botol', 'slug' => 'kartini-hijau-botol', 'deskripsi' => 'Warna hijau botol yang pekat dan mewah untuk gaya klasik.', 'ukuran_tersedia' => 'M,L,XL', 'harga_sewa' => 235000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 2, 'nama_kebaya' => 'Kartini Beludru Klasik', 'slug' => 'kartini-beludru-klasik', 'deskripsi' => 'Kebaya Kartini dari bahan beludru (velvet) yang biasa dikenakan priyayi.', 'ukuran_tersedia' => 'L', 'harga_sewa' => 280000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],

            // ====================================================================
            // Kategori 3: Kebaya Bali
            // ====================================================================
            ['id_kategori' => 3, 'nama_kebaya' => 'Kebaya Bali Brokat Kuning', 'slug' => 'kebaya-bali-brokat-kuning', 'deskripsi' => 'Kebaya Bali dari brokat semi-prancis warna kuning cerah, lengkap dengan obi.', 'ukuran_tersedia' => 'S,M', 'harga_sewa' => 250000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 1],
            ['id_kategori' => 3, 'nama_kebaya' => 'Kebaya Bali Katun Putih', 'slug' => 'kebaya-bali-katun-putih', 'deskripsi' => 'Kebaya Bali sederhana dari katun untuk persembahyangan, nyaman dan sejuk.', 'ukuran_tersedia' => 'Semua Ukuran', 'harga_sewa' => 150000, 'stok' => 3, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 1],
            ['id_kategori' => 3, 'nama_kebaya' => 'Kebaya Bali Merah Jambu', 'slug' => 'kebaya-bali-merah-jambu', 'deskripsi' => 'Warna pink fanta yang ceria pada kebaya Bali modern.', 'ukuran_tersedia' => 'M,L', 'harga_sewa' => 220000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 3, 'nama_kebaya' => 'Kebaya Bali Lengan Lonceng', 'slug' => 'kebaya-bali-lengan-lonceng', 'deskripsi' => 'Modifikasi kebaya Bali dengan model lengan lonceng yang trendi.', 'ukuran_tersedia' => 'S,M,L', 'harga_sewa' => 230000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'disewa', 'rekomendasi' => 0],
            ['id_kategori' => 3, 'nama_kebaya' => 'Kebaya Bali Endek Klungkung', 'slug' => 'kebaya-bali-endek-klungkung', 'deskripsi' => 'Kebaya Bali dengan aksen kain tenun Endek khas Klungkung.', 'ukuran_tersedia' => 'L,XL', 'harga_sewa' => 280000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 3, 'nama_kebaya' => 'Kebaya Bali Ungu Lavender', 'slug' => 'kebaya-bali-ungu-lavender', 'deskripsi' => 'Warna ungu lavender yang lembut pada kebaya brokat Bali.', 'ukuran_tersedia' => 'M,L', 'harga_sewa' => 260000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 3, 'nama_kebaya' => 'Kebaya Bali Modifikasi Sabuk', 'slug' => 'kebaya-bali-modifikasi-sabuk', 'deskripsi' => 'Kebaya Bali modern dengan sabuk yang sudah menyatu pada kebaya.', 'ukuran_tersedia' => 'S,M', 'harga_sewa' => 240000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 3, 'nama_kebaya' => 'Kebaya Bali Tile Mutiara', 'slug' => 'kebaya-bali-tile-mutiara', 'deskripsi' => 'Bahan tile dengan taburan mutiara yang mewah untuk acara spesial.', 'ukuran_tersedia' => 'M,L', 'harga_sewa' => 300000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 3, 'nama_kebaya' => 'Kebaya Bali Hijau Mint', 'slug' => 'kebaya-bali-hijau-mint', 'deskripsi' => 'Warna hijau mint yang segar pada kebaya Bali.', 'ukuran_tersedia' => 'S,M,L', 'harga_sewa' => 225000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 3, 'nama_kebaya' => 'Kebaya Bali Hitam Gold', 'slug' => 'kebaya-bali-hitam-gold', 'deskripsi' => 'Perpaduan brokat hitam dengan benang emas yang elegan dan mewah.', 'ukuran_tersedia' => 'M,L,XL', 'harga_sewa' => 290000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],

            // ====================================================================
            // Kategori 4: Kebaya Encim
            // ====================================================================
            ['id_kategori' => 4, 'nama_kebaya' => 'Encim Bordir Khas Betawi', 'slug' => 'encim-bordir-khas-betawi', 'deskripsi' => 'Kebaya Encim katun voal dengan bordir kerancang khas Betawi.', 'ukuran_tersedia' => 'M,L', 'harga_sewa' => 250000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 1],
            ['id_kategori' => 4, 'nama_kebaya' => 'Encim Putih Klasik', 'slug' => 'encim-putih-klasik', 'deskripsi' => 'Kebaya Encim putih dengan bordir warna senada, sangat anggun.', 'ukuran_tersedia' => 'S,M,L', 'harga_sewa' => 230000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 1],
            ['id_kategori' => 4, 'nama_kebaya' => 'Encim Merah Menyala', 'slug' => 'encim-merah-menyala', 'deskripsi' => 'Kebaya Encim warna merah cerah, cocok untuk perayaan Imlek.', 'ukuran_tersedia' => 'M,L', 'harga_sewa' => 260000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 4, 'nama_kebaya' => 'Encim Biru Pastel', 'slug' => 'encim-biru-pastel', 'deskripsi' => 'Warna biru pastel yang lembut pada kebaya Encim modern.', 'ukuran_tersedia' => 'S,M', 'harga_sewa' => 240000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 4, 'nama_kebaya' => 'Encim Lengan Pendek', 'slug' => 'encim-lengan-pendek', 'deskripsi' => 'Versi modern kebaya Encim dengan lengan pendek yang lebih kasual.', 'ukuran_tersedia' => 'S,M,L', 'harga_sewa' => 200000, 'stok' => 3, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 4, 'nama_kebaya' => 'Encim Bordir Phoenix', 'slug' => 'encim-bordir-phoenix', 'deskripsi' => 'Bordiran megah berbentuk burung Phoenix pada kebaya Encim.', 'ukuran_tersedia' => 'L,XL', 'harga_sewa' => 300000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'disewa', 'rekomendasi' => 0],
            ['id_kategori' => 4, 'nama_kebaya' => 'Encim Hijau Giok', 'slug' => 'encim-hijau-giok', 'deskripsi' => 'Warna hijau giok yang mewah dan klasik pada kebaya Encim.', 'ukuran_tersedia' => 'M,L', 'harga_sewa' => 270000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 4, 'nama_kebaya' => 'Encim Oranye Segar', 'slug' => 'encim-oranye-segar', 'deskripsi' => 'Kebaya Encim dengan warna oranye yang segar dan ceria.', 'ukuran_tersedia' => 'S,M', 'harga_sewa' => 235000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 4, 'nama_kebaya' => 'Encim Gradasi Warna', 'slug' => 'encim-gradasi-warna', 'deskripsi' => 'Kebaya Encim modern dengan efek gradasi warna yang unik.', 'ukuran_tersedia' => 'M,L', 'harga_sewa' => 280000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 4, 'nama_kebaya' => 'Encim Katun Jepang', 'slug' => 'encim-katun-jepang', 'deskripsi' => 'Dibuat dari bahan katun jepang yang adem dengan bordir minimalis.', 'ukuran_tersedia' => 'S,M,L', 'harga_sewa' => 220000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],

            // ====================================================================
            // Kategori 5: Kebaya Modern
            // ====================================================================
            ['id_kategori' => 5, 'nama_kebaya' => 'Kebaya Modern Peplum', 'slug' => 'kebaya-modern-peplum', 'deskripsi' => 'Kebaya dengan potongan peplum di bagian pinggang untuk siluet modern.', 'ukuran_tersedia' => 'S,M,L', 'harga_sewa' => 280000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 1],
            ['id_kategori' => 5, 'nama_kebaya' => 'Kebaya Asimetris Dusty Pink', 'slug' => 'kebaya-asimetris-dusty-pink', 'deskripsi' => 'Potongan asimetris yang edgy dengan warna dusty pink yang manis.', 'ukuran_tersedia' => 'M,L', 'harga_sewa' => 300000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 1],
            ['id_kategori' => 5, 'nama_kebaya' => 'Kebaya Cape Brokat', 'slug' => 'kebaya-cape-brokat', 'deskripsi' => 'Kebaya modern dengan tambahan cape (jubah) brokat yang menjuntai.', 'ukuran_tersedia' => 'Semua Ukuran', 'harga_sewa' => 320000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 5, 'nama_kebaya' => 'Kebaya Kutubaru Tanpa Bef', 'slug' => 'kebaya-kutubaru-tanpa-bef', 'deskripsi' => 'Modifikasi Kutu Baru tanpa bef untuk tampilan lebih simpel dan modern.', 'ukuran_tersedia' => 'S,M,L', 'harga_sewa' => 250000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 5, 'nama_kebaya' => 'Kebaya Lengan Balon', 'slug' => 'kebaya-lengan-balon', 'deskripsi' => 'Aksen lengan balon (puff sleeves) yang sedang tren pada kebaya.', 'ukuran_tersedia' => 'S,M', 'harga_sewa' => 290000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 5, 'nama_kebaya' => 'Kebaya Organza Transparan', 'slug' => 'kebaya-organza-transparan', 'deskripsi' => 'Outer kebaya dari bahan organza yang ringan dan transparan.', 'ukuran_tersedia' => 'M,L', 'harga_sewa' => 270000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'disewa', 'rekomendasi' => 0],
            ['id_kategori' => 5, 'nama_kebaya' => 'Kebaya Drapery Satin', 'slug' => 'kebaya-drapery-satin', 'deskripsi' => 'Kebaya modern dari satin dengan aksen drapery yang jatuh menawan.', 'ukuran_tersedia' => 'M,L', 'harga_sewa' => 310000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 5, 'nama_kebaya' => 'Kebaya Kerah Sabrina', 'slug' => 'kebaya-kerah-sabrina', 'deskripsi' => 'Kebaya dengan kerah sabrina (off-shoulder) yang sensual dan modern.', 'ukuran_tersedia' => 'S,M', 'harga_sewa' => 285000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 5, 'nama_kebaya' => 'Kebaya Two-Tone', 'slug' => 'kebaya-two-tone', 'deskripsi' => 'Perpaduan dua warna kontras dalam satu desain kebaya modern.', 'ukuran_tersedia' => 'M,L,XL', 'harga_sewa' => 330000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 5, 'nama_kebaya' => 'Kebaya Detail Ruffle', 'slug' => 'kebaya-detail-ruffle', 'deskripsi' => 'Hiasan ruffle vertikal atau horizontal untuk sentuhan feminin.', 'ukuran_tersedia' => 'S,M,L', 'harga_sewa' => 295000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],

            // ====================================================================
            // Kategori 6: Kebaya Pengantin
            // ====================================================================
            ['id_kategori' => 6, 'nama_kebaya' => 'Gaun Kebaya Pengantin Putih', 'slug' => 'gaun-kebaya-pengantin-putih', 'deskripsi' => 'Gaun kebaya panjang menjuntai warna putih dengan taburan payet mewah.', 'ukuran_tersedia' => 'M,L', 'harga_sewa' => 800000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 1],
            ['id_kategori' => 6, 'nama_kebaya' => 'Kebaya Pengantin Adat Sunda', 'slug' => 'kebaya-pengantin-adat-sunda', 'deskripsi' => 'Kebaya pengantin putih klasik untuk siger Sunda, lengkap dengan bordir.', 'ukuran_tersedia' => 'S,M,L', 'harga_sewa' => 750000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 1],
            ['id_kategori' => 6, 'nama_kebaya' => 'Kebaya Akad Nikah Broken White', 'slug' => 'kebaya-akad-nikah-broken-white', 'deskripsi' => 'Warna broken white yang lembut untuk kebaya akad nikah, bahan tile prancis.', 'ukuran_tersedia' => 'M', 'harga_sewa' => 700000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 6, 'nama_kebaya' => 'Kebaya Pengantin Beludru Hitam', 'slug' => 'kebaya-pengantin-beludru-hitam', 'deskripsi' => 'Kebaya pengantin adat Jawa (dodotan) dari beludru hitam dengan benang emas.', 'ukuran_tersedia' => 'L,XL', 'harga_sewa' => 900000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 6, 'nama_kebaya' => 'Kebaya Resepsi Gold Mewah', 'slug' => 'kebaya-resepsi-gold-mewah', 'deskripsi' => 'Kebaya modern warna emas untuk resepsi, penuh dengan detail kristal.', 'ukuran_tersedia' => 'M,L', 'harga_sewa' => 1000000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'disewa', 'rekomendasi' => 0],
            ['id_kategori' => 6, 'nama_kebaya' => 'Kebaya Pengantin Muslimah Syari', 'slug' => 'kebaya-pengantin-muslimah-syari', 'deskripsi' => 'Gaun kebaya syari yang tertutup namun tetap anggun untuk hari spesial.', 'ukuran_tersedia' => 'Semua Ukuran', 'harga_sewa' => 850000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 6, 'nama_kebaya' => 'Kebaya Pengantin Merah Marun', 'slug' => 'kebaya-pengantin-merah-marun', 'deskripsi' => 'Pilihan warna berani merah marun untuk kebaya pengantin modern.', 'ukuran_tersedia' => 'S,M', 'harga_sewa' => 780000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 6, 'nama_kebaya' => 'Kebaya Pemberkatan Simpel Elegan', 'slug' => 'kebaya-pemberkatan-simpel-elegan', 'deskripsi' => 'Kebaya putih selutut yang simpel dan elegan untuk pemberkatan.', 'ukuran_tersedia' => 'S,M', 'harga_sewa' => 650000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 6, 'nama_kebaya' => 'Kebaya Pengantin Adat Bali', 'slug' => 'kebaya-pengantin-adat-bali', 'deskripsi' => 'Kebaya Payas Agung Bali yang megah dan penuh warna.', 'ukuran_tersedia' => 'M,L', 'harga_sewa' => 950000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 6, 'nama_kebaya' => 'Kebaya Pengantin Champagne', 'slug' => 'kebaya-pengantin-champagne', 'deskripsi' => 'Warna champagne yang hangat dan mewah untuk gaun kebaya pernikahan.', 'ukuran_tersedia' => 'M', 'harga_sewa' => 820000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],

            // ====================================================================
            // Kategori 7: Kebaya Wisuda
            // ====================================================================
            ['id_kategori' => 7, 'nama_kebaya' => 'Kebaya Wisuda Navy Elegan', 'slug' => 'kebaya-wisuda-navy-elegan', 'deskripsi' => 'Kebaya Kutu Baru modern warna navy, pilihan populer untuk wisuda.', 'ukuran_tersedia' => 'S,M,L', 'harga_sewa' => 250000, 'stok' => 3, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 1],
            ['id_kategori' => 7, 'nama_kebaya' => 'Kebaya Wisuda Nude Pastel', 'slug' => 'kebaya-wisuda-nude-pastel', 'deskripsi' => 'Warna nude yang lembut dan kalem, mudah dipadukan dengan berbagai warna jilbab.', 'ukuran_tersedia' => 'M,L', 'harga_sewa' => 260000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 1],
            ['id_kategori' => 7, 'nama_kebaya' => 'Kebaya Wisuda Lengan Lonceng', 'slug' => 'kebaya-wisuda-lengan-lonceng', 'deskripsi' => 'Kebaya wisuda dengan detail lengan lonceng yang cantik.', 'ukuran_tersedia' => 'S,M', 'harga_sewa' => 270000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 7, 'nama_kebaya' => 'Kebaya Wisuda Brokat Lilac', 'slug' => 'kebaya-wisuda-brokat-lilac', 'deskripsi' => 'Warna lilac yang sedang tren pada kebaya brokat untuk wisuda.', 'ukuran_tersedia' => 'M', 'harga_sewa' => 280000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'disewa', 'rekomendasi' => 0],
            ['id_kategori' => 7, 'nama_kebaya' => 'Kebaya Wisuda Model Tunik', 'slug' => 'kebaya-wisuda-model-tunik', 'deskripsi' => 'Kebaya tunik panjang menutupi panggul, cocok untuk yang berhijab.', 'ukuran_tersedia' => 'M,L,XL', 'harga_sewa' => 300000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 7, 'nama_kebaya' => 'Kebaya Wisuda Merah Marun', 'slug' => 'kebaya-wisuda-merah-marun', 'deskripsi' => 'Warna marun yang memberikan kesan dewasa dan formal.', 'ukuran_tersedia' => 'S,M,L', 'harga_sewa' => 255000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 7, 'nama_kebaya' => 'Kebaya Wisuda Organza Layer', 'slug' => 'kebaya-wisuda-organza-layer', 'deskripsi' => 'Kebaya dengan outer organza yang memberikan dimensi.', 'ukuran_tersedia' => 'S,M', 'harga_sewa' => 290000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 7, 'nama_kebaya' => 'Kebaya Wisuda Simpel Abu-abu', 'slug' => 'kebaya-wisuda-simpel-abu-abu', 'deskripsi' => 'Kebaya simpel berwarna abu-abu, elegan dan tidak berlebihan.', 'ukuran_tersedia' => 'M,L', 'harga_sewa' => 240000, 'stok' => 3, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 7, 'nama_kebaya' => 'Kebaya Wisuda Hijau Sage', 'slug' => 'kebaya-wisuda-hijau-sage', 'deskripsi' => 'Warna hijau sage yang menenangkan dan sedang populer.', 'ukuran_tersedia' => 'S,M,L', 'harga_sewa' => 275000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 7, 'nama_kebaya' => 'Kebaya Wisuda Aksen Selendang', 'slug' => 'kebaya-wisuda-aksen-selendang', 'deskripsi' => 'Kebaya dengan selendang yang menyatu di bahu, praktis dan cantik.', 'ukuran_tersedia' => 'M,L', 'harga_sewa' => 285000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],

            // ====================================================================
            // Kategori 8: Kebaya Brokat
            // ====================================================================
            ['id_kategori' => 8, 'nama_kebaya' => 'Brokat Semi Prancis Nude', 'slug' => 'brokat-semi-prancis-nude', 'deskripsi' => 'Kebaya dari bahan brokat semi prancis yang lembut dengan warna nude.', 'ukuran_tersedia' => 'S,M,L', 'harga_sewa' => 300000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 1],
            ['id_kategori' => 8, 'nama_kebaya' => 'Brokat Cornelli Tumpuk', 'slug' => 'brokat-cornelli-tumpuk', 'deskripsi' => 'Kebaya dari brokat cornelli dengan tekstur timbul yang khas.', 'ukuran_tersedia' => 'M,L', 'harga_sewa' => 320000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 1],
            ['id_kategori' => 8, 'nama_kebaya' => 'Brokat Warna Silver Metalik', 'slug' => 'brokat-warna-silver-metalik', 'deskripsi' => 'Tampil beda dengan kebaya brokat warna silver yang glamor.', 'ukuran_tersedia' => 'M', 'harga_sewa' => 350000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 8, 'nama_kebaya' => 'Tunik Brokat Panjang', 'slug' => 'tunik-brokat-panjang', 'deskripsi' => 'Tunik panjang dari bahan brokat, cocok untuk berbagai acara formal.', 'ukuran_tersedia' => 'L,XL', 'harga_sewa' => 330000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 8, 'nama_kebaya' => 'Brokat Klasik Gold', 'slug' => 'brokat-klasik-gold', 'deskripsi' => 'Kebaya model klasik dari bahan brokat berwarna emas.', 'ukuran_tersedia' => 'M,L', 'harga_sewa' => 310000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'disewa', 'rekomendasi' => 0],
            ['id_kategori' => 8, 'nama_kebaya' => 'Brokat Model Sabrina', 'slug' => 'brokat-model-sabrina', 'deskripsi' => 'Kebaya brokat modern dengan potongan kerah sabrina (off-shoulder).', 'ukuran_tersedia' => 'S,M', 'harga_sewa' => 290000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 8, 'nama_kebaya' => 'Brokat Hitam Elegan', 'slug' => 'brokat-hitam-elegan', 'deskripsi' => 'Kebaya brokat hitam yang tidak pernah salah untuk acara malam hari.', 'ukuran_tersedia' => 'S,M,L', 'harga_sewa' => 280000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 8, 'nama_kebaya' => 'Brokat Warna Pastel', 'slug' => 'brokat-warna-pastel', 'deskripsi' => 'Kebaya brokat dengan pilihan warna-warna pastel yang lembut.', 'ukuran_tersedia' => 'S,M', 'harga_sewa' => 295000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 8, 'nama_kebaya' => 'Brokat Full Furing', 'slug' => 'brokat-full-furing', 'deskripsi' => 'Kebaya brokat yang sudah dilapisi furing (dalaman) penuh sehingga tidak transparan.', 'ukuran_tersedia' => 'Semua Ukuran', 'harga_sewa' => 270000, 'stok' => 3, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 8, 'nama_kebaya' => 'Brokat Model Asimetris', 'slug' => 'brokat-model-asimetris', 'deskripsi' => 'Potongan bawah kebaya yang asimetris dari bahan brokat.', 'ukuran_tersedia' => 'M,L', 'harga_sewa' => 340000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],

            // ====================================================================
            // Kategori 9: Kebaya Jumputan
            // ====================================================================
            ['id_kategori' => 9, 'nama_kebaya' => 'Jumputan Palembang Merah', 'slug' => 'jumputan-palembang-merah', 'deskripsi' => 'Kebaya dari kain jumputan asli Palembang dengan warna dasar merah.', 'ukuran_tersedia' => 'M,L,XL', 'harga_sewa' => 280000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 1],
            ['id_kategori' => 9, 'nama_kebaya' => 'Tunik Jumputan Pelangi', 'slug' => 'tunik-jumputan-pelangi', 'deskripsi' => 'Tunik modern dengan corak jumputan warna-warni seperti pelangi.', 'ukuran_tersedia' => 'Semua Ukuran', 'harga_sewa' => 300000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 1],
            ['id_kategori' => 9, 'nama_kebaya' => 'Jumputan Model Kutu Baru', 'slug' => 'jumputan-model-kutu-baru', 'deskripsi' => 'Gaya Kutu Baru yang diaplikasikan pada kain jumputan yang etnik.', 'ukuran_tersedia' => 'S,M,L', 'harga_sewa' => 270000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 9, 'nama_kebaya' => 'Jumputan Warna Indigo', 'slug' => 'jumputan-warna-indigo', 'deskripsi' => 'Kebaya jumputan dengan pewarnaan alami indigo (biru tua).', 'ukuran_tersedia' => 'M,L', 'harga_sewa' => 320000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 9, 'nama_kebaya' => 'Outerwear Jumputan', 'slug' => 'outerwear-jumputan', 'deskripsi' => 'Luaran (outer) panjang dari kain jumputan untuk gaya kasual-etnik.', 'ukuran_tersedia' => 'Semua Ukuran', 'harga_sewa' => 250000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 9, 'nama_kebaya' => 'Jumputan Sutra Elegan', 'slug' => 'jumputan-sutra-elegan', 'deskripsi' => 'Kain jumputan dari bahan sutra yang jatuh dan mewah.', 'ukuran_tersedia' => 'M,L', 'harga_sewa' => 350000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'disewa', 'rekomendasi' => 0],
            ['id_kategori' => 9, 'nama_kebaya' => 'Dress Jumputan Modern', 'slug' => 'dress-jumputan-modern', 'deskripsi' => 'Terusan (dress) modern dengan motif jumputan.', 'ukuran_tersedia' => 'S,M,L', 'harga_sewa' => 290000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 9, 'nama_kebaya' => 'Jumputan Kombinasi Polos', 'slug' => 'jumputan-kombinasi-polos', 'deskripsi' => 'Kebaya yang memadukan kain jumputan dengan kain polos sebagai aksen.', 'ukuran_tersedia' => 'M,L,XL', 'harga_sewa' => 275000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 9, 'nama_kebaya' => 'Jumputan Hijau Botol', 'slug' => 'jumputan-hijau-botol', 'deskripsi' => 'Warna dasar hijau botol yang pekat pada kain jumputan.', 'ukuran_tersedia' => 'L,XL', 'harga_sewa' => 285000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 9, 'nama_kebaya' => 'Setelan Celana Jumputan', 'slug' => 'setelan-celana-jumputan', 'deskripsi' => 'Setelan atasan kebaya dan celana dari kain jumputan yang serasi.', 'ukuran_tersedia' => 'S,M', 'harga_sewa' => 310000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],

            // ====================================================================
            // Kategori 10: Kebaya Songket
            // ====================================================================
            ['id_kategori' => 10, 'nama_kebaya' => 'Kebaya Kurung Songket', 'slug' => 'kebaya-kurung-songket', 'deskripsi' => 'Baju kurung khas Melayu dengan aksen songket yang mewah.', 'ukuran_tersedia' => 'M,L,XL', 'harga_sewa' => 350000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 1],
            ['id_kategori' => 10, 'nama_kebaya' => 'Kebaya Aksen Songket Palembang', 'slug' => 'kebaya-aksen-songket-palembang', 'deskripsi' => 'Kebaya polos dengan aksen kain songket Palembang di bagian pinggang dan lengan.', 'ukuran_tersedia' => 'S,M,L', 'harga_sewa' => 320000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 1],
            ['id_kategori' => 10, 'nama_kebaya' => 'Setelan Kebaya dan Rok Songket', 'slug' => 'setelan-kebaya-dan-rok-songket', 'deskripsi' => 'Setelan lengkap kebaya brokat dengan bawahan rok dari kain songket.', 'ukuran_tersedia' => 'M,L', 'harga_sewa' => 400000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 10, 'nama_kebaya' => 'Kebaya Merah dengan Songket Emas', 'slug' => 'kebaya-merah-dengan-songket-emas', 'deskripsi' => 'Perpaduan kebaya merah menyala dengan kemewahan songket benang emas.', 'ukuran_tersedia' => 'M,L', 'harga_sewa' => 450000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 10, 'nama_kebaya' => 'Rompi Songket Modern', 'slug' => 'rompi-songket-modern', 'deskripsi' => 'Rompi atau vest dari kain songket untuk dipadukan dengan kemeja atau kebaya.', 'ukuran_tersedia' => 'Semua Ukuran', 'harga_sewa' => 280000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 10, 'nama_kebaya' => 'Kebaya Hitam Aksen Songket Silver', 'slug' => 'kebaya-hitam-aksen-songket-silver', 'deskripsi' => 'Kebaya hitam dengan aksen songket benang perak yang modern dan elegan.', 'ukuran_tersedia' => 'S,M', 'harga_sewa' => 380000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'disewa', 'rekomendasi' => 0],
            ['id_kategori' => 10, 'nama_kebaya' => 'Kebaya Pengantin Songket', 'slug' => 'kebaya-pengantin-songket', 'deskripsi' => 'Kebaya pengantin megah yang menggunakan songket sebagai bahan utamanya.', 'ukuran_tersedia' => 'M', 'harga_sewa' => 700000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 10, 'nama_kebaya' => 'Tunik Songket Asli', 'slug' => 'tunik-songket-asli', 'deskripsi' => 'Tunik yang seluruhnya terbuat dari kain tenun songket asli.', 'ukuran_tersedia' => 'L,XL', 'harga_sewa' => 500000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 10, 'nama_kebaya' => 'Kebaya Biru Dongker dan Songket', 'slug' => 'kebaya-biru-dongker-dan-songket', 'deskripsi' => 'Paduan warna navy yang kalem dengan kilau kain songket.', 'ukuran_tersedia' => 'S,M,L', 'harga_sewa' => 360000, 'stok' => 2, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
            ['id_kategori' => 10, 'nama_kebaya' => 'Kebaya Peplum Aksen Songket', 'slug' => 'kebaya-peplum-aksen-songket', 'deskripsi' => 'Kebaya peplum modern dengan bagian peplum terbuat dari kain songket.', 'ukuran_tersedia' => 'M,L', 'harga_sewa' => 390000, 'stok' => 1, 'foto' => 'default.png', 'status' => 'tersedia', 'rekomendasi' => 0],
        ];

        $this->db->table('kebaya')->insertBatch($data);
    }
}
