<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class KebayaSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'id_kategori' => 1,
                'nama_kebaya' => 'Kebaya Pengantin Modern Sutera Mutiara',
                'slug' => 'kebaya-pengantin-modern-sutera-mutiara',
                'deskripsi' => 'Kebaya pengantin modern dengan bahan sutera mutiara berkualitas tinggi, detail payet dan bordir tangan yang mewah.',
                'ukuran_tersedia' => 'S,M,L,XL',
                'harga_sewa' => 750000,
                'stok' => 3,
                'foto' => 'default.png',
                'status' => 'tersedia',
                'rekomendasi' => 1,
            ],
            [
                'id_kategori' => 1,
                'nama_kebaya' => 'Kebaya Pengantin Tradisional Brokat Emas',
                'slug' => 'kebaya-pengantin-tradisional-brokat-emas',
                'deskripsi' => 'Kebaya pengantin tradisional dengan brokat emas khas Jawa, dilengkapi dengan kain jarik batik premium.',
                'ukuran_tersedia' => 'M,L,XL',
                'harga_sewa' => 850000,
                'stok' => 2,
                'foto' => 'default.png',
                'status' => 'tersedia',
                'rekomendasi' => 1,
            ],
            [
                'id_kategori' => 1,
                'nama_kebaya' => 'Kebaya Pengantin A-Line Payet Kristal',
                'slug' => 'kebaya-pengantin-a-line-payet-kristal',
                'deskripsi' => 'Kebaya pengantin model A-Line dengan hiasan payet kristal Swarovski, desain modern yang elegan.',
                'ukuran_tersedia' => 'S,M,L',
                'harga_sewa' => 900000,
                'stok' => 1,
                'foto' => 'default.png',
                'status' => 'tersedia',
                'rekomendasi' => 0,
            ],
            [
                'id_kategori' => 1,
                'nama_kebaya' => 'Kebaya Pengantin Bali Lengkap Aksesoris',
                'slug' => 'kebaya-pengantin-bali-lengkap-aksesoris',
                'deskripsi' => 'Kebaya pengantin khas Bali lengkap dengan aksesoris tradisional seperti sanggul dan hiasan kepala.',
                'ukuran_tersedia' => 'All Size',
                'harga_sewa' => 950000,
                'stok' => 2,
                'foto' => 'default.png',
                'status' => 'tersedia',
                'rekomendasi' => 1,
            ],
            [
                'id_kategori' => 1,
                'nama_kebaya' => 'Kebaya Pengantin Vintage Lace',
                'slug' => 'kebaya-pengantin-vintage-lace',
                'deskripsi' => 'Kebaya pengantin bergaya vintage dengan material lace impor dari Perancis, cocok untuk tema pernikahan klasik.',
                'ukuran_tersedia' => 'S,M',
                'harga_sewa' => 800000,
                'stok' => 1,
                'foto' => 'default.png',
                'status' => 'tersedia',
                'rekomendasi' => 0,
            ],

            [
                'id_kategori' => 2,
                'nama_kebaya' => 'Kebaya Wisuda Modern Pastel',
                'slug' => 'kebaya-wisuda-modern-pastel',
                'deskripsi' => 'Kebaya wisuda dengan warna pastel lembut dan desain modern yang youthful.',
                'ukuran_tersedia' => 'S,M,L,XL',
                'harga_sewa' => 350000,
                'stok' => 5,
                'foto' => 'default.png',
                'status' => 'tersedia',
                'rekomendasi' => 1,
            ],
            [
                'id_kategori' => 2,
                'nama_kebaya' => 'Kebaya Wisuda Brokat Silver',
                'slug' => 'kebaya-wisuda-brokat-silver',
                'deskripsi' => 'Kebaya wisuda dengan bahan brokat silver yang elegan dan mewah.',
                'ukuran_tersedia' => 'M,L,XL',
                'harga_sewa' => 400000,
                'stok' => 3,
                'foto' => 'default.png',
                'status' => 'tersedia',
                'rekomendasi' => 0,
            ],
            [
                'id_kategori' => 2,
                'nama_kebaya' => 'Kebaya Wisuda Minimalis',
                'slug' => 'kebaya-wisuda-minimalis',
                'deskripsi' => 'Kebaya wisuda desain minimalis tanpa hiasan berlebihan, cocok untuk yang suka kesederhanaan.',
                'ukuran_tersedia' => 'S,M,L',
                'harga_sewa' => 300000,
                'stok' => 4,
                'foto' => 'default.png',
                'status' => 'tersedia',
                'rekomendasi' => 0,
            ],
            [
                'id_kategori' => 2,
                'nama_kebaya' => 'Kebaya Wisuda Floral Embroidery',
                'slug' => 'kebaya-wisuda-floral-embroidery',
                'deskripsi' => 'Kebaya wisuda dengan sulaman bunga yang indah, memberikan kesan feminin dan anggun.',
                'ukuran_tersedia' => 'S,M',
                'harga_sewa' => 450000,
                'stok' => 2,
                'foto' => 'default.png',
                'status' => 'tersedia',
                'rekomendasi' => 1,
            ],
            [
                'id_kategori' => 2,
                'nama_kebaya' => 'Kebaya Wisuda Two Tone',
                'slug' => 'kebaya-wisuda-two-tone',
                'deskripsi' => 'Kebaya wisuda kombinasi dua warna dengan potongan modern yang stylish.',
                'ukuran_tersedia' => 'All Size',
                'harga_sewa' => 380000,
                'stok' => 3,
                'foto' => 'default.png',
                'status' => 'tersedia',
                'rekomendasi' => 0,
            ],
            [
                'id_kategori' => 3,
                'nama_kebaya' => 'Kebaya Pesta Brokat Royal',
                'slug' => 'kebaya-pesta-brokat-royal',
                'deskripsi' => 'Kebaya pesta dengan brokat royal quality, sangat cocok untuk acara formal.',
                'ukuran_tersedia' => 'S,M,L,XL',
                'harga_sewa' => 500000,
                'stok' => 2,
                'foto' => 'default.png',
                'status' => 'tersedia',
                'rekomendasi' => 1,
            ],
            [
                'id_kategori' => 4,
                'nama_kebaya' => 'Kebaya Jawa Klasik',
                'slug' => 'kebaya-jawa-klasik',
                'deskripsi' => 'Kebaya tradisional Jawa dengan model klasik dan bahan katun halus.',
                'ukuran_tersedia' => 'All Size',
                'harga_sewa' => 250000,
                'stok' => 4,
                'foto' => 'default.png',
                'status' => 'tersedia',
                'rekomendasi' => 0,
            ],
            [
                'id_kategori' => 5,
                'nama_kebaya' => 'Kebaya Modern Asymmetrical',
                'slug' => 'kebaya-modern-asymmetrical',
                'deskripsi' => 'Kebaya modern dengan potongan asymmetrical yang unik dan fashionable.',
                'ukuran_tersedia' => 'S,M,L',
                'harga_sewa' => 400000,
                'stok' => 3,
                'foto' => 'default.png',
                'status' => 'tersedia',
                'rekomendasi' => 1,
            ],
        ];

        $this->db->table('kebaya')->insertBatch($data);
    }
}